apiVersion: v1
kind: Namespace
metadata:
  name: serverless-examples
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: serverless-example-nodejs
  namespace: serverless-examples
spec:
  template:
    spec:
      containers:
        - image: docker.io/kscout/serverless-example-nodejs
          env:
            - name: APP_PORT
              value: "3000"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
